# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
  # args:
  # - 'run'
  # - 'deploy'
  # - 'cloudrunservice'
  # - '--image'
  # - 'gcr.io/$PROJECT_ID/Tasuku-APIs'
  # - '--region'
  # - 'asia-southeast1'
  # - '--platform'
  # - 'managed'
  # - '--allow-unauthenticated'
  
# steps:
# - name: 'gcr.io/cloud-builders/mvn'
  # args: ['install']
# - name: 'gcr.io/cloud-builders/docker'
  # args: ['build', '--tag=gcr.io/$PROJECT_ID/tasuku-api', '.']
# images: ['gcr.io/$PROJECT_ID/tasuku-api']

# steps:
# - name: 'gcr.io/$PROJECT_ID/tasuku-api'
  # args: ['mvn', 'appengine:deploy']
  
# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
  # args: ['app', 'deploy']
  
# steps:
# - name: 'gcr.io/cloud-builders/mvn'
  # args: ['install']
# - name: 'gcr.io/cloud-builders/docker'
  # args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot', '.']
# images: ['gcr.io/$PROJECT_ID/spring-boot']

steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '/workspace/src/main/appengine/app.yaml']
  dir: "target"