# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy']

steps:
# Install
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  
# Build
- name: 'gcr.io/cloud-builders/nvm'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot', '.']
images: ['gcr.io/$PROJECT_ID/spring-boot']

# Deploy

